task_dir: "."
port: 9001
server_name: potato annotator
annotation_task_name: Politeness rating
output_annotation_dir: annotation_output/full/
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- data_files/politeness_rating_3718.csv
item_properties:
  id_key: id
  text_key: text
list_as_text:
  text_list_prefix_type: None
  horizontal: true
user_config:
  allow_all_users: true
  users: []
login:
  type: url_direct
  url_argument: PROLIFIC_PID
jumping_to_id_disabled: true
hide_navbar: true
surveyflow:
  'on': true
  order:
  - pre_annotation
  - post_annotation
  pre_annotation:
  - surveyflow/intro.jsonl
  - surveyflow/instruction.jsonl
  - surveyflow/consent.jsonl
  post_annotation:
  - surveyflow/experience.jsonl
  - surveyflow/demographic_questions.jsonl
  - surveyflow/end.jsonl
  testing:
  - surveyflow/testing.jsonl
prestudy:
  'on': false
  minimum_score: 0.8
  groundtruth_key: whether_match
  question_key: Whether the presented sentences are discussing the same scientific
    finding
  answer_mapping:
    'Yes': true
    'No': false
  pass_page: surveyflow/prestudy_pass.jsonl
  fail_page: surveyflow/prestudy_fail.jsonl
automatic_assignment:
  'on': true
  output_filename: task_assignment.json
  sampling_strategy: random
  labels_per_instance: 8
  instance_per_annotator: 50
  test_question_per_annotator: 0
  users: []
alert_time_each_instance: 10000000
horizontal_key_bindings: true
annotation_schemes:
- annotation_type: likert
  name: Consider you read this email from a colleague, how polite do you think it
    is?
  description: Consider you read this email from a colleague, how polite do you think
    it is?
  min_label: Not polite at all
  max_label: Very polite
  label_requirement:
    required: true
  size: 5
  sequential_key_binding: true
site_dir: default
