annotation_task_name: Empty Example
task_dir: .
output_annotation_dir: annotation_output/your-task-name/
output_annotation_format: csv
annotation_codebook_url: ''
data_files: []
item_properties:
  id_key: id
  text_key: text
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes: []
site_dir: default
