port: 9001
server_name: potato annotator
annotation_task_name: Example for using kwargs
output_annotation_dir: annotation_output/kwarg-example/annotations
task_dir: annotation_output/kwarg-example/
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- data/kwarg-example.csv
item_properties:
  id_key: id
  text_key: text
  kwargs:
  - my_kwarg
  - my_other_kwarg
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 1000000
annotation_schemes:
- annotation_type: likert
  name: kwarg_coolness
  description: How cool are kwargs?
  min_label: Not very cool
  max_label: Totally cool
  size: 7
site_dir: default
