annotation_task_name: Simple Slider Example
task_dir: .
output_annotation_dir: annotation_output/simple-slider/
output_annotation_format: csv
annotation_codebook_url: ''
data_files:
- data/toy-example.json
item_properties:
  id_key: id
  text_key: text
user_config:
  allow_all_users: true
  users: []
annotation_schemes:
- annotation_type: slider
  name: awesomeness
  description: How awesome is this?
  min_value: 0
  max_value: 100
  starting_value: 50
alert_time_each_instance: 10000000
site_dir: potato/templates/
