port: 9001
server_name: potato annotator
annotation_task_name: Simple Text Box Example
task_dir: annotation_output/simple-text-box/
output_annotation_dir: annotation_output/simple-text-box/
output_annotation_format: csv
annotation_codebook_url: ''
data_files:
- data/toy-example.json
item_properties:
  id_key: id
  text_key: text
  context_key: context
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: text
  name: textbox_input
  description: How does this text make you feel?
  labels:
  - happy?
  - sad?
  textarea:
    'on': false
    rows: 2
    cols: 40
site_dir: default
