port: 9001
server_name: potato annotator
annotation_task_name: Simple Check Box Example
task_dir: annotation_output/simple-check-box/
output_annotation_dir: annotation_output/simple-check-box/annotations
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- data/dynamic-labels.json
item_properties:
  id_key: id
  text_key: text
  context_key: context
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: multiselect
  name: appropriateness
  description: Which of the following reply is appropriate?
  dynamic_labels: true
  labels:
  - name: '{{instance_obj.labels[0]}}'
  - name: '{{instance_obj.labels[1]}}'
  - name: '{{instance_obj.labels[2]}}'
  sequential_key_binding: true
site_dir: default
