task_dir: .
port: 9001
server_name: potato annotator
annotation_task_name: Simple Video as Label Example
output_annotation_dir: annotation_output/simple-video-as-label/
output_annotation_format: json
annotation_codebook_url: ''
data_files:
- data/video-label-example.json
item_properties:
  id_key: id
  text_key: text
  context_key: context
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: multiselect
  name: GIF Reply Appropriateness
  video_as_label: 'True'
  description: Select all appropriate GIF replies.
  labels:
  - name: '{{instance_obj.gifs[0]}}'
    videopath: data/files/{{instance_obj.gifs_path[0]}}
  - name: '{{instance_obj.gifs[1]}}'
    videopath: data/files/{{instance_obj.gifs_path[1]}}
  - name: '{{instance_obj.gifs[2]}}'
    videopath: data/files/{{instance_obj.gifs_path[2]}}
  sequential_key_binding: true
site_dir: default
