port: 9001
server_name: potato annotator
annotation_task_name: Simple Highlighting Example
task_dir: .
output_annotation_dir: annotation_output/
output_annotation_format: json
annotation_codebook_url: ''
data_files:
- data/toy-example.csv
item_properties:
  id_key: id
  text_key: text
  context_key: context
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: span
  name: certainty
  description: Highlight which phrases make the sentence more or less certain
  labels:
  - certain
  - uncertain
  sequential_key_binding: true
site_dir: default
