port: 9001
server_name: potato annotator
annotation_task_name: Simple Best-Worst-Scaling Example
task_dir: annotation_output/simple-bws/
output_annotation_dir: annotation_output/simple-bws/annotations
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- data/bws-example.json
item_properties:
  id_key: id
  text_key: text
list_as_text:
  text_list_prefix_type: alphabet
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: radio
  name: bws_best
  description: Which is the most positive sentence?
  horizontal: true
  labels:
  - A
  - B
  - C
  - D
  - E
  sequential_key_binding: true
- annotation_type: radio
  name: bws_worst
  description: Which is the most negative sentence?
  horizontal: true
  labels:
  - A
  - B
  - C
  - D
  - E
  sequential_key_binding: true
site_dir: default
