port: 9001
server_name: potato annotator
annotation_task_name: Simple Pairwise Comparison Example
task_dir: .
output_annotation_dir: annotation_output/simple-pairwise/
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- data/pairwise-example.json
item_properties:
  id_key: id
  text_key: text
list_as_text:
  text_list_prefix_type: alphabet
user_config:
  allow_all_users: true
  users: []
jumping_to_id_disabled: true
surveyflow:
  'on': false
  order:
  - pre_annotation
  - post_annotation
  pre_annotation:
  - data/surveyflow/intro.jsonl
  - data/surveyflow/consent.jsonl
  post_annotation:
  - data/surveyflow/demographic_questions.jsonl
  - data/surveyflow/end.jsonl
automatic_assignment:
  'on': false
  output_filename: task_assignment.json
  sampling_strategy: random
  labels_per_instance: 2
  instance_per_annotator: 1
  users: []
alert_time_each_instance: 10000000
horizontal_key_bindings: true
annotation_schemes:
- annotation_type: radio
  name: pairwise_comparison
  description: Which tweet is more intimate
  horizontal: false
  labels:
  - A is more intimate
  - B is more intimate
  - Hard to tell
  label_requirement:
    required: true
  sequential_key_binding: true
site_dir: default
