port: 9001
server_name: potato annotator
annotation_task_name: Simple Single-Choice Example
task_dir: annotation_output/simple-radio-selection/
output_annotation_dir: annotation_output/simple-radio-selection/annotations
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- data/toy-example.json
item_properties:
  id_key: id
  text_key: text
  context_key: context
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: radio
  name: favorite_color
  description: What food does this text make you want to eat?
  labels:
  - pizza
  - bagels
  - burgers
  - curry
  - tacos
  sequential_key_binding: true
site_dir: default
