task_dir: ".."
port: 9001
server_name: potato annotator
annotation_task_name: Simple Video as Input Example
output_annotation_dir: annotation_output/simple-video-as-input/
output_annotation_format: json
annotation_codebook_url: ''
data_files:
- data/video-as-input.json
item_properties:
  id_key: id
  text_key: text
  context_key: context
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: multiselect
  name: GIF Reply Appropriateness
  description: How do you feel about this video?
  labels:
  - Happy
  - Sad
  - Angry
  sequential_key_binding: true
site_dir: default
