annotation_task_name: Simple Multirate Example
task_dir: annotation_output/simple-multirate/
output_annotation_dir: annotation_output/simple-multirate/annotations
output_annotation_format: csv
annotation_codebook_url: ''
data_files:
- data/toy-example.json
item_properties:
  id_key: id
  text_key: text
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: multirate
  name: awesomeness
  description: How awesome is this?
  display_config:
    num_columns: 1
  options:
  - Option 1
  - Option 2
  - Option 3
  labels:
  - Strongly disagree
  - Disagree
  - Neutral
  - Agree
  - Strongly Agree
  label_requirement:
    required: true
  sequential_key_binding: true
  option_randomization: true
site_dir: default
