task_dir: "."
port: 9001
server_name: potato annotator
annotation_task_name: Summarization evaluation
output_annotation_dir: annotation_output/
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- data_files/toy-example.json
item_properties:
  id_key: id
  text_key: text
  context_key: context
user_config:
  allow_all_users: true
  users: []
login:
  type: url_direct
  url_argument: PROLIFIC_PID
jumping_to_id_disabled: false
hide_navbar: true
automatic_assignment:
  'on': false
  output_filename: task_assignment.json
  sampling_strategy: random
  labels_per_instance: 3
  instance_per_annotator: 3
  test_question_per_annotator: 0
  users: []
list_as_text:
  text_list_prefix_type: none
  horizontal: true
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: likert
  name: relevance
  description: Relevance
  min_label: Not Relevant
  max_label: Super Relevant
  size: 5
  sequential_key_binding: true
  displaying_score: true
  label_requirement:
    required: true
- annotation_type: likert
  name: fluency
  description: Fluency
  min_label: Not fluent
  max_label: Super fluent
  size: 5
  sequential_key_binding: true
  displaying_score: true
  label_requirement:
    required: true
- annotation_type: likert
  name: coherence
  description: Coherence
  min_label: Not Coherent
  max_label: Super Coherent
  size: 5
  sequential_key_binding: true
  displaying_score: true
  label_requirement:
    required: true
- annotation_type: radio
  name: consistency
  description: Factual consistency
  labels:
  - consistent
  - not consistent
  sequential_key_binding: true
  horizontal: true
  label_requirement:
    required: true
site_dir: default
