task_dir: "."
port: 9001
server_name: potato annotator
annotation_task_name: Dialogue Analysis
output_annotation_dir: annotation_output/
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- data_files/dialogue-example.json
item_properties:
  id_key: id
  text_key: text
  context_key: context
user_config:
  allow_all_users: true
  users: []
list_as_text:
  text_list_prefix_type: none
  alternating_shading: true
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: span
  name: certainty
  description: Highlight which phrases make the sentence more or less certain
  labels:
  - certain
  - uncertain
  sequential_key_binding: true
- annotation_type: radio
  name: sentiment
  description: What kind of sentiment does the given text hold?
  labels:
  - positive
  - neutral
  - negative
  sequential_key_binding: true
site_dir: default
