port: 9001
server_name: potato annotator
annotation_task_name: Question Answering
output_annotation_dir: annotation_output/question-answering/
output_annotation_format: csv
annotation_codebook_url: ''
data_files:
- data_files/toy-example.json
item_properties:
  id_key: id
  text_key: text
  context_key: context
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: text
  name: textbox_input
  description: Please write your own reply to the given sentence
site_dir: default
