port: 8000
server_name: potato annotator
annotation_task_name: Immigration Framing
output_annotation_dir: annotation_output/
task_dir: .
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- data_files/framing_tweets.json
item_properties:
  id_key: id
  text_key: text
user_config:
  allow_all_users: true
  users: []
keyword_highlights_file: frame_keywords.tsv
alert_time_each_instance: 10000000
horizontal_key_bindings: true
annotation_schemes:
- annotation_type: multiselect
  name: Issue-General
  description: Issue-General
  labels:
  - name: Economic
    tooltip_file: tooltips/ig_economic.html
  - name: Capacity and Resources
    tooltip_file: tooltips/ig_capacity.html
  - name: Morality and Ethics
    tooltip_file: tooltips/ig_morality.html
  - name: Fairness and Equality
    tooltip_file: tooltips/ig_fairness.html
  - name: Legality, Constitutionality, Jurisdiction
    tooltip_file: tooltips/ig_legality.html
  - name: Crime and Punishment
    tooltip_file: tooltips/ig_crime.html
  - name: Security and Defense
    tooltip_file: tooltips/ig_security.html
  - name: Health and Safety
    tooltip_file: tooltips/ig_health.html
  - name: Quality of Life
    tooltip_file: tooltips/ig_quality.html
  - name: Cultural Identity
    tooltip_file: tooltips/ig_cultural.html
  - name: Public Sentiment
    tooltip_file: tooltips/ig_public.html
  - name: Political Factors and Implications
    tooltip_file: tooltips/ig_political.html
  - name: Policy Prescription and Evaluation
    tooltip_file: tooltips/ig_policy.html
  - name: External Regulation and Reputation
    tooltip_file: tooltips/ig_external.html
  - None
- annotation_type: multiselect
  name: Issue-Specific
  description: Issue-Specific
  labels:
  - name: 'Victim: Global Economy'
    tooltip_file: tooltips/sp_global.html
  - name: 'Victim: Humanitarian'
    tooltip_file: tooltips/sp_humanitarian.html
  - name: 'Victim: War'
    tooltip_file: tooltips/sp_war.html
  - name: 'Victim: Discrimination'
    tooltip_file: tooltips/sp_discrimination.html
  - name: 'Hero: Cultural Diversity'
    tooltip_file: tooltips/sp_diversity.html
  - name: 'Hero: Integration'
    tooltip_file: tooltips/sp_integration.html
  - name: 'Hero: Worker'
    tooltip_file: tooltips/sp_worker.html
  - name: 'Threat: Jobs'
    tooltip_file: tooltips/sp_jobs.html
  - name: 'Threat: Public Order'
    tooltip_file: tooltips/sp_order.html
  - name: 'Threat: Fiscal'
    tooltip_file: tooltips/sp_fiscal.html
  - name: 'Threat: National Cohesion'
    tooltip_file: tooltips/sp_cohesion.html
  - None
- annotation_type: multiselect
  name: Narrative
  description: Narrative
  labels:
  - name: Episodic
    tooltip_file: tooltips/narr_episodic.html
  - name: Thematic
    tooltip_file: tooltips/narr_thematic.html
  - None
site_dir: default
