{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Immigration Framing",

    "output_dir": "../output/",

    # NOTE: This is probably going to be a directory / DB at some point...
    "user_state_dir": "annotation_output",

    "annotation_codebook_url": "https://docs.google.com/document/d/1eXgaOZJDahhZLqYWbLTD_84-d1rnQ4M-bccer3HY6WI",

    "data_files": [
       "potato/data/framing_tweets.json"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text"

    },

    "users": [
        {"user_id": "0", "firstname": "David", "lastname": "Jurgens"},
        {"user_id": "1", "firstname": "Jiaxin", "lastname": "Pei"},
        {"user_id": "2", "firstname": "Naitian", "lastname": "Zhou"}
    ],

    "annotation_files": [
        "../data/examples"
    ],

    "keyword_highlights_file": "config/frame_keywords.tsv",

    "annotation_schemes": [
        {
            "annotation_type": "multiselect",
            "single_select":"True",
            "name": "Issue-General",
            "labels": [
                { "name": "Economic",
                  "tooltip_file": "config/tooltips/ig_economic.html",
                  "key_value": '1'
                },
                {
                  "name": "Capacity and Resources",
                  "tooltip_file": "config/tooltips/ig_capacity.html",
                  "key_value": '2'
                 },

                { "name": "Morality and Ethics",
                  "tooltip_file": "config/tooltips/ig_morality.html",
                  "key_value": '3'
                },

                { "name": "Fairness and Equality",
                  "tooltip_file": "config/tooltips/ig_fairness.html",
                  "key_value": '4'
                },
                { "name": "Legality, Constitutionality, Jurisdiction",
                  "tooltip_file": "config/tooltips/ig_legality.html",
                  "key_value": '5'
                },
                { "name": "Crime and Punishment",
                  "tooltip_file": "config/tooltips/ig_crime.html",
                  "key_value": '6'
                },
                { "name": "Security and Defense",
                  "tooltip_file": "config/tooltips/ig_security.html",
                  "key_value": '7'
                },
                { "name": "Health and Safety",
                  "tooltip_file": "config/tooltips/ig_health.html",
                  "key_value": '8'
                },
                { "name": "Quality of Life",
                  "tooltip_file": "config/tooltips/ig_quality.html",
                  "key_value": '9'
                },
                { "name": "Cultural Identity",
                  "tooltip_file": "config/tooltips/ig_cultural.html",
                  "key_value": '0'
                },
                { "name": "Public Sentiment",
                  "tooltip_file": "config/tooltips/ig_public.html",
                  "key_value": 'q'
                },
                { "name": "Political Factors and Implications",
                  "tooltip_file": "config/tooltips/ig_political.html",
                  "key_value": 'w'
                },
                { "name": "Policy Prescription and Evaluation",
                  "tooltip_file": "config/tooltips/ig_policy.html",
                  "key_value": 'e'
                },
                { "name": "External Regulation and Reputation",
                  "tooltip_file": "config/tooltips/ig_external.html",
                  "key_value": 'r'

                },
                "None"
            ]
        },

        {
            "annotation_type": "multiselect",
            "name": "Issue-Specific",
            "labels": [

                { "name": "Victim: Global Economy",
                  "tooltip_file": "config/tooltips/sp_global.html"
                },
                { "name": "Victim: Humanitarian",
                  "tooltip_file": "config/tooltips/sp_humanitarian.html"
                },
                { "name": "Victim: War",
                  "tooltip_file": "config/tooltips/sp_war.html"
                },
                { "name": "Victim: Discrimination",
                  "tooltip_file": "config/tooltips/sp_discrimination.html"
                },
                { "name": "Hero: Cultural Diversity",
                  "tooltip_file": "config/tooltips/sp_diversity.html"
                },
                { "name": "Hero: Integration",
                  "tooltip_file": "config/tooltips/sp_integration.html"
                },
                { "name": "Hero: Worker",
                  "tooltip_file": "config/tooltips/sp_worker.html"
                },
                { "name": "Threat: Jobs",
                  "tooltip_file": "config/tooltips/sp_jobs.html"
                },
                { "name": "Threat: Public Order",
                  "tooltip_file": "config/tooltips/sp_order.html"
                },
                { "name": "Threat: Fiscal",
                  "tooltip_file": "config/tooltips/sp_fiscal.html"
                },
                { "name": "Threat: National Cohesion",
                  "tooltip_file": "config/tooltips/sp_cohesion.html"
                },
                "None"
            ]

        },

        {
            "annotation_type": "multiselect",
            "name": "Narrative",
            "labels": [
                {
                   "name": "Episodic",
                   "tooltip_file": "config/tooltips/narr_episodic.html",
                },
                {
                  "name": "Thematic",
                  "tooltip_file": "config/tooltips/narr_thematic.html"
                },
                "None"
            ]

        }

    ],


    # Visualization
    "html_template": "templates/single_multiple_choice.html",
    "header_file": "templates/header.html",

    # This is where the actual HTML files will be generated
    "site_dir": "potato/templates/",

    # comment
    "state_update_rate": 1,


}