task_dir: ".."
annotation_task_name: Empathy Annotation
output_annotation_dir: annotation_output/empathy/
output_annotation_format: csv
annotation_codebook_url: ''
data_files:
- data_files/empathy.json
item_properties:
  id_key: id
  text_key: text
list_as_text:
  text_list_prefix_type: none
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: likert
  name: rating
  description: To what extent does the observer's appraisal of the situation match
    that of the target speaker?
  min_label: Not at all
  max_label: Completely
  size: 5
  sequential_key_binding: true
site_dir: default
