task_dir: "."
port: 9001
server_name: potato annotator
annotation_task_name: Aspect-level-Uncertainty
output_annotation_dir: annotation_output/aspect_level/
annotation_codebook_url: ''
data_files:
- data_files/news_abs_finding_sample.json
output_annotation_format: tsv
item_properties:
  id_key: id
  text_key: finding
user_config:
  allow_all_users: true
  users: []
keyword_highlights_file: configs/uncertainty_keywords.tsv
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: multiselect
  name: Aspects
  description: Do the following aspects present in the given finding?
  labels:
  - name: Number
    tooltip_file: uncertainty_tooltips/aspect_level/number.html
    key_value: q
  - name: Extent
    tooltip_file: uncertainty_tooltips/aspect_level/extent.html
    key_value: w
  - name: Probability/Effect/Connection
    tooltip_file: uncertainty_tooltips/aspect_level/probability.html
    key_value: e
  - name: Condition
    tooltip_file: uncertainty_tooltips/aspect_level/condition.html
    key_value: r
  - name: Suggestion/Action
    tooltip_file: uncertainty_tooltips/aspect_level/suggestion.html
    key_value: t
  - name: Framing
    tooltip_file: uncertainty_tooltips/aspect_level/framing.html
    key_value: y
  - name: None
    tooltip: All the labels do not apply here
    exclude_other: 'True'
    key_value: None
  - name: Bad-Text
    tooltip: This is not a scientific finding
    exclude_other: 'True'
    key_value: BAD
- annotation_type: multiselect
  name: Which-is-uncertain
  description: Are the presented aspects uncertain?
  labels:
  - name: Number
    tooltip_file: uncertainty_tooltips/aspect_level/number.html
    key_value: a
  - name: Extent
    tooltip_file: uncertainty_tooltips/aspect_level/extent.html
    key_value: s
  - name: Probability/Effect/Connection
    tooltip_file: uncertainty_tooltips/aspect_level/probability.html
    key_value: d
  - name: Condition
    tooltip_file: uncertainty_tooltips/aspect_level/condition.html
    key_value: f
  - name: Suggestion/Action
    tooltip_file: uncertainty_tooltips/aspect_level/suggestion.html
    key_value: g
  - name: Framing
    tooltip_file: uncertainty_tooltips/aspect_level/framing.html
    key_value: h
  - name: None
    tooltip: All the labels do not apply here
    exclude_other: 'True'
    key_value: None
  - name: Bad-Text
    tooltip: This is not a scientific finding
    exclude_other: 'True'
    key_value: BAD
site_dir: default
