task_dir: ".."
port: 9001
server_name: potato annotator
annotation_task_name: Sentence-level-Uncertainty
output_annotation_dir: annotation_output/sentence_level/
annotation_codebook_url: ''
data_files:
- data_files/news_abs_finding_sample.json
output_annotation_format: tsv
item_properties:
  id_key: id
  text_key: finding
user_config:
  allow_all_users: true
  users: []
keyword_highlights_file: configs/uncertainty_keywords.tsv
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: multiselect
  single_select: 'True'
  name: Sentence-Level-Uncertainty
  description: How certain do you feel about the given scientific finding
  labels:
  - name: '1. Very uncertain '
    tooltip_file: uncertainty_tooltips/sentence_level/1.html
    key_value: '1'
  - name: 2. Uncertain
    tooltip_file: uncertainty_tooltips/sentence_level/2.html
    key_value: '2'
  - name: 3. Somewhat uncertain
    tooltip_file: uncertainty_tooltips/sentence_level/3.html
    key_value: '3'
  - name: 4. Somewhat certain
    tooltip_file: uncertainty_tooltips/sentence_level/4.html
    key_value: '4'
  - name: 5. Certain
    tooltip_file: uncertainty_tooltips/sentence_level/5.html
    key_value: '5'
  - name: 6. Very certain
    tooltip_file: uncertainty_tooltips/sentence_level/6.html
    key_value: '6'
  - name: 7. None
    tooltip: This is not a scientific finding
    exclude_other: 'True'
    key_value: None
site_dir: default
