task_dir: "."
port: 9001
server_name: potato annotator
annotation_task_name: Match finding
output_annotation_dir: projects/match_finding_likert/annotation_output/pilot/
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- projects/match_finding_likert/data_files/pilot_data.csv
item_properties:
  id_key: id
  text_key: text
list_as_text:
  text_list_prefix_type: None
  horizontal: true
user_config:
  allow_all_users: true
  users: []
require_no_password: true
jumping_to_id_disabled: false
hide_navbar: true
surveyflow:
  'on': true
  order:
  - pre_annotation
  - post_annotation
  pre_annotation:
  - projects/match_finding_likert/surveyflow/introduction.jsonl
  - projects/match_finding_likert/surveyflow/1_Completely_different.jsonl
  - projects/match_finding_likert/surveyflow/2_Mostly_different.jsonl
  - projects/match_finding_likert/surveyflow/3_Somewhat_similar.jsonl
  - projects/match_finding_likert/surveyflow/4_Mostly_the_same.jsonl
  - projects/match_finding_likert/surveyflow/5_Completely_the_same.jsonl
  - projects/match_finding_likert/surveyflow/consent.jsonl
  - projects/match_finding_likert/surveyflow/instruction.jsonl
  prestudy_passed:
  - projects/match_finding_likert/surveyflow/prestudy_pass.jsonl
  prestudy_failed:
  - projects/match_finding_likert/surveyflow/prestudy_fail.jsonl
  post_annotation:
  - projects/match_finding_likert/surveyflow/experience.jsonl
  - projects/match_finding_likert/surveyflow/end.jsonl
  testing:
  - projects/match_finding_likert/surveyflow/testing.jsonl
prestudy:
  'on': false
  minimum_score: 0.8
  groundtruth_key: whether_match
  question_key: Whether the presented sentences are discussing the same scientific
    finding
  answer_mapping:
    'Yes': true
    'No': false
  pass_page: projects/match_finding_likert/surveyflow/prestudy_pass.jsonl
  fail_page: projects/match_finding_likert/surveyflow/prestudy_fail.jsonl
automatic_assignment:
  'on': true
  output_filename: task_assignment.json
  'sampling_strategy:': random
  labels_per_instance: 5
  instance_per_annotator: 50
  test_question_per_annotator: 0
  users: []
alert_time_each_instance: 10000000
horizontal_key_bindings: true
annotation_schemes:
- annotation_type: likert
  name: The information conveyed in the findings is
  description: The information conveyed in the findings is
  labels:
  - name: Completely different
    tooltip: Sentences in this category have findings which convey completely different
      information
    key_value: '1'
  - name: Mostly different
    tooltip: The findings may talk about the same topic, but the actual information
      is mostly different; for example, these sentences convey mostly different information
      even though they talk about the same topic
    key_value: '2'
  - name: Somewhat similar
    tooltip: The findings are discussing relevant research outputs but there are some
      differences in the overall information conveyed
    key_value: '3'
  - name: Mostly the same
    tooltip: two sentences are describing the mostly the same information but at different
      levels of generality, or one could support the other
    key_value: '4'
  - name: Completely the same
    tooltip: complete overlap in the information in the findings conveyed by the two
      sentences
    key_value: '5'
  has_free_response:
    instruction: 'Comments (optional):'
  displaying_score: true
  label_requirement:
    required: true
site_dir: potato/templates/
