task_dir: ".."
port: 9001
server_name: potato annotator
annotation_task_name: Match finding
output_annotation_dir: annotation_output/pilot/
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- data_files/pilot_data.csv
- data_files/prestudy/prestudy_data.csv
item_properties:
  id_key: id
  text_key: text
list_as_text:
  text_list_prefix_type: None
  horizontal: true
user_config:
  allow_all_users: true
  users: []
login:
  type: url_direct
  url_argument: PROLIFIC_PID
require_no_password: true
jumping_to_id_disabled: false
hide_navbar: true
surveyflow:
  'on': true
  order:
  - pre_annotation
  - prestudy_passed
  - prestudy_failed
  - post_annotation
  pre_annotation:
  - surveyflow/intro.jsonl
  - surveyflow/examples.jsonl
  - surveyflow/consent.jsonl
  - surveyflow/instruction.jsonl
  - surveyflow/prestudy_intro.jsonl
  prestudy_passed:
  - surveyflow/prestudy_pass.jsonl
  prestudy_failed:
  - surveyflow/prestudy_fail.jsonl
  post_annotation:
  - surveyflow/experience.jsonl
  - surveyflow/end.jsonl
  testing:
  - surveyflow/testing.jsonl
prestudy:
  'on': true
  minimum_score: 0.8
  groundtruth_key: whether_match
  question_key: Whether the presented sentences are discussing the same scientific
    finding
  answer_mapping:
    'Yes': true
    'No': false
  pass_page: surveyflow/prestudy_pass.jsonl
  fail_page: surveyflow/prestudy_fail.jsonl
automatic_assignment:
  'on': true
  output_filename: task_assignment.json
  'sampling_strategy:': random
  labels_per_instance: 5
  instance_per_annotator: 5
  test_question_per_annotator: 0
  users: []
alert_time_each_instance: 10000000
horizontal_key_bindings: true
annotation_schemes:
- annotation_type: radio
  name: Whether the presented sentences are discussing the same scientific finding
  description: Whether the presented sentences are discussing the same scientific
    finding
  labels:
  - 'Yes'
  - 'No'
  has_free_response:
    instruction: 'Comments:'
  label_requirement:
    required: true
  sequential_key_binding: true
site_dir: default
