{
    "port": 9001,


    "task_dir": "..",
    "server_name": "potato annotator",

    "annotation_task_name": "Sentiment Analysis",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv",

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "",

    "data_files": [
       "data_files/toy-example.csv"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
        "context_key": "context"
    },


    "user_config": {

      "allow_all_users": True,

      "users": [  ],
    },

    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,

    "annotation_schemes": [
      {
        "annotation_type": "likert",
        "name": "sentiment",
        "description": "What is the sentiment of this text?",
        "min_label": "Very negative",
        "max_label": "Very positive",
        "label_requirement": { "required": True },
        "size": 5,
        "sequential_key_binding": True,
      }
    ],
    "site_dir": "default"

}
