{
    "port": 9001,

    "server_name": "potato annotator",    
    
    "annotation_task_name": "Example for using kwargs",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/kwarg-example/",
    
    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv", 

    "annotation_codebook_url": "",

    "data_files": [
       "data/kwarg-example.csv"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
        "kwargs": ["my_kwarg", "my_other_kwarg"]
    },

    "user_config_path": "potato/user_config.json",

    "user_config": {
      "allow_all_users": True,
      "users": [ ] 
    },


    "alert_time_each_instance": 1000000,
        
    
    "annotation_schemes": [

        {
          "annotation_type": "likert",
          "name": "kwarg_coolness",
          "description": "How cool are kwargs?",
          "min_label": "Not very cool",
          "max_label": "Totally cool",
          "size": 7,
        },          
    ],


    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces

    "html_layout": "templates/examples/kwargs_example.html",
    #"html_layout": "templates/examples/plain_layout.html",

    # If the HTML layout requires Potato to position individual annotation
    # elements, then set this flag to True
    "custom_layout": False,

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    "base_html_template": "templates/base_template.html",
    "header_file": "templates/header.html",
    

    # This is where the actual HTML files will be generated
    "site_dir": "potato/templates/",

    # comment
    "state_update_rate": 1,


}
