port: 9001
server_name: potato annotator
annotation_task_name: Squad QA
output_annotation_dir: annotation_output/full/
output_annotation_format: tsv
annotation_codebook_url: ''
data_files:
- data_files/squad_1000.csv
item_properties:
  id_key: id
  text_key: text
list_as_text:
  text_list_prefix_type: None
  horizontal: true
user_config:
  allow_all_users: true
  users: []
login:
  type: url_direct
  url_argument: PROLIFIC_PID
jumping_to_id_disabled: true
hide_navbar: true
surveyflow:
  'on': true
  order:
  - pre_annotation
  - post_annotation
  pre_annotation:
  - surveyflow/intro.jsonl
  - surveyflow/instruction.jsonl
  - surveyflow/consent.jsonl
  prestudy_passed:
  - surveyflow/prestudy_pass.jsonl
  prestudy_failed:
  - surveyflow/prestudy_fail.jsonl
  post_annotation:
  - surveyflow/experience.jsonl
  - surveyflow/demographic_questions.jsonl
  - surveyflow/end.jsonl
  testing: []
prestudy:
  'on': false
  minimum_score: 0.8
  groundtruth_key: whether_match
  question_key: Whether the presented sentences are discussing the same scientific
    finding
  answer_mapping:
    'Yes': true
    'No': false
  pass_page: surveyflow/prestudy_pass.jsonl
  fail_page: surveyflow/prestudy_fail.jsonl
automatic_assignment:
  'on': true
  output_filename: task_assignment.json
  sampling_strategy: random
  labels_per_instance: 5
  instance_per_annotator: 10
  test_question_per_annotator: 0
  users: []
alert_time_each_instance: 10000000
horizontal_key_bindings: true
annotation_schemes:
- annotation_type: highlight
  name: Answer the question through highlighting the paragraph
  description: Answer the question through highlighting the paragraph
  labels:
  - Answer
  bad_text_label:
    label_content: No answer is given in this document
  label_requirement:
    required: true
  sequential_key_binding: false
- annotation_type: likert
  name: How difficult do you think this question is?
  description: How difficult do you think this question is?
  min_label: Not difficult at all
  max_label: Very difficult
  label_requirement:
    required: true
  size: 5
  sequential_key_binding: false
site_dir: default
